import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Overthinking: Understanding the Pattern and Finding Support',
  description: 'Learn what people mean by overthinking, how it can affect everyday life, and when an online counselling conversation may help.',
  alternates: { canonical: '/support/overthinking' },
  openGraph: { title: 'Overthinking: Understanding the Pattern | Mannosaar', description: 'A practical, non-diagnostic guide to overthinking and finding support.', url: '/support/overthinking' },
};

export default function OverthinkingPage() {
  return <main className="bg-[#cbb7df] text-[#34213f]"><article className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#5b267a]">Everyday emotional challenges</p><h1 className="mt-4 font-playfair text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl">Overthinking: understanding the pattern and finding support.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#4c4052]">People often use “overthinking” to describe getting caught in repeated thoughts, possible outcomes or old conversations. It is a common way of describing an experience, not a diagnosis.</p><div className="mt-12 space-y-10 border-t border-[#6f4b88]/30 pt-8"><section><h2 className="font-playfair text-3xl font-bold">What overthinking can feel like</h2><p className="mt-4 text-base leading-8 text-[#4c4052]">You may replay a conversation, look for certainty before making a decision, imagine what could go wrong or find it hard to settle your mind at night. The pattern can become tiring when it takes attention away from sleep, work, study or relationships.</p></section><section><h2 className="font-playfair text-3xl font-bold">A few gentle reflection ideas</h2><ul className="mt-4 space-y-3 text-base leading-8 text-[#4c4052]"><li>Write down the thought and separate what you know from what you are predicting.</li><li>Give yourself a short, defined time to reflect, then return to one concrete activity.</li><li>Notice whether the thought needs action, a conversation or simply acknowledgement.</li><li>Talk with someone you trust when the same loop keeps returning.</li></ul></section><section><h2 className="font-playfair text-3xl font-bold">When a conversation may help</h2><p className="mt-4 text-base leading-8 text-[#4c4052]">An experienced counsellor can offer a structured space to understand patterns and consider practical next steps. <Link href="/counselling/individual" className="font-bold text-[#5b267a] underline underline-offset-4">Online individual counselling</Link> may be worth exploring if overthinking is affecting daily life or relationships.</p></section></div><div className="mt-12 border-t border-[#6f4b88]/30 pt-7 text-sm leading-7 text-[#4c4052]"><p>This page is educational and does not diagnose or treat a medical condition. For severe or persistent symptoms, speak with an appropriately qualified healthcare professional. Mannosaar is not an emergency service.</p><p className="mt-4"><Link href="/blogs" className="font-bold text-[#5b267a] underline underline-offset-4">Explore more resources</Link> or <Link href="/book-session" className="font-bold text-[#5b267a] underline underline-offset-4">book a conversation</Link>.</p></div></article></main>;
}
