import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Stress and Emotional Overwhelm: Finding Support',
  description: 'Understand everyday stress and emotional overwhelm, try practical reflection steps, and learn when online counselling may be useful.',
  alternates: { canonical: '/support/stress' },
  openGraph: { title: 'Stress and Emotional Overwhelm | Mannosaar', description: 'A practical guide to recognising stress and finding support.', url: '/support/stress' },
};

export default function StressSupportPage() {
  return <main className="bg-[#cbb7df] text-[#34213f]"><article className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#5b267a]">Everyday emotional challenges</p><h1 className="mt-4 font-playfair text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl">Stress and emotional overwhelm: finding support.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#4c4052]">Stress can show up when the demands around you feel greater than the time, energy or support available. Understanding what is happening can make it easier to choose a next step.</p><div className="mt-12 space-y-10 border-t border-[#6f4b88]/30 pt-8"><section><h2 className="font-playfair text-3xl font-bold">How stress can affect everyday life</h2><p className="mt-4 text-base leading-8 text-[#4c4052]">Some people notice irritability, tiredness, difficulty concentrating, changes in sleep or less patience in relationships. These experiences can have many causes, so they are not a diagnosis on their own.</p></section><section><h2 className="font-playfair text-3xl font-bold">Small ways to make space</h2><ul className="mt-4 space-y-3 text-base leading-8 text-[#4c4052]"><li>Name the demand that is taking the most energy and identify one part you can influence.</li><li>Take a short break without treating rest as something that must be earned.</li><li>Write down the tasks, conversations or decisions that need attention instead of holding them all in your head.</li><li>Ask for practical help or emotional support before the pressure becomes unmanageable.</li></ul></section><section><h2 className="font-playfair text-3xl font-bold">Finding a supported space</h2><p className="mt-4 text-base leading-8 text-[#4c4052]">Talking with a professional may help you understand what is contributing to the pressure and what kind of change feels realistic. <Link href="/counselling/individual" className="font-bold text-[#5b267a] underline underline-offset-4">Individual online counselling</Link> offers a private place to begin that conversation.</p></section></div><div className="mt-12 border-t border-[#6f4b88]/30 pt-7 text-sm leading-7 text-[#4c4052]"><p>This page is educational and does not diagnose or treat a medical condition. For severe or persistent symptoms, speak with an appropriately qualified healthcare professional. Mannosaar is not an emergency service.</p><p className="mt-4"><Link href="/blogs" className="font-bold text-[#5b267a] underline underline-offset-4">Read more resources</Link> or <Link href="/book-session" className="font-bold text-[#5b267a] underline underline-offset-4">book a conversation</Link>.</p></div></article></main>;
}
